[workspace]
root = "."
package_manager = "pnpm"
ignore = [
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "coverage",
    "*.log",
    "tmp",
    "temp",
]

[[tasks]]
name = "build"
pkg_name = "*"
desc = "构建所有包"
command = "npm run build"

[[tasks]]
name = "test"
pkg_name = "*"
desc = "运行测试"
command = "npm run test"

[[tasks]]
name = "lint"
pkg_name = "*"
desc = "代码检查"
command = "npm run lint"

[[tasks]]
name = "build-frontend"
desc = "构建前端相关包"
command = "npm run build"
packages = ["web-ui", "mobile-app", "shared-components"]

[[tasks]]
name = "test-packages"
desc = "测试指定的包"
command = "build"
packages = ["@test/pkg1", "@test/pkg2"]

[[tasks]]
name = "build:editor"
desc = "构建编辑器相关包（无 pkg_name 字段测试）"
command = "build"
packages = ["@test/pkg1"]



[execution]
max_concurrency = 10
task_timeout = 300
retry_count = 1
continue_on_failure = false

[output]
show_progress = true
verbose = false
colored = true

[i18n]
language = "zh_cn"
