max_width = 100
hard_tabs = false
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
edition = "2021"
normalize_doc_attributes = true
format_code_in_doc_comments = true
wrap_comments = true 